name: CI

on:
  push:
    branches:
      - '**'
  repository_dispatch:
    types:
      check_connector_for_breaking_changes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup Ballerina Environment
      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: latest

      # Build Ballerina Project
      - name: Ballerina Build
        run: bal pack
        working-directory: ./ballerina
        env:
          JAVA_HOME: /usr/lib/jvm/default-jvm

      # Push to Ballerina Staging Central
      - name: Push to Staging
        run: bal push
        env:
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_STAGE_ACCESS_TOKEN }}
          WORKING_DIR: ./random
          JAVA_HOME: /usr/lib/jvm/default-jvm

      # Test Ballerina Project
      - name: Ballerina Test
        run: bal test ./ballerina --test-report --code-coverage --coverage-format=xml
        env:
          WORKING_DIR: ./calendar
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          REFRESH_URL: ${{ secrets.REFRESH_URL }}
          JAVA_HOME: /usr/lib/jvm/default-jvm

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

      # Send notification when build fails
      - name: Alert notifier on failure
        if: failure() && (github.event.action == 'check_connector_for_breaking_changes')
        run: |
          curl -X POST \
          'https://api.github.com/repos/ballerina-platform/ballerina-release/dispatches' \
          --header 'Accept: application/vnd.github.v3+json' \
          --header 'Authorization: Bearer ${{ secrets.BALLERINA_BOT_TOKEN }}' \
          --data-raw '{
            "event_type": "notify-ballerinax-connector-build-failure",
            "client_payload": {
              "repoName": "module-ballerinax-googleapis.calendar",
              "workflow": "CI"
            }
          }'
